### ISSUE TITLE
Windows OSQuery Enrollment Failing

### ISSUE THREAD

**Issue by ahmed-awadelkarim** [zentralopensource/zentral#101]
Two issues I'm experiencing with OSQuery Enrollment. 

1. OSQuery Enrollment psi, configured to include osquery 4.5.1 doesn't include osquery msi.
2. After manually installing osqueryd and rerunning the install scripts, my machine still fails to enroll. Flags are below:

`--tls_hostname=<zentralhost>
--enroll_tls_endpoint=/osquery/enroll
--enroll_secret_path=C:\Program Files\osquery\enrollment_secret.txt
--config_plugin=tls
--config_tls_endpoint=/osquery/config
--logger_plugin=tls
--logger_tls_endpoint=/osquery/log
--logger_tls_period=60
--logger_tls_compress=true
--disable_distributed=false
--distributed_plugin=tls
--distributed_tls_read_endpoint=/osquery/distributed/read
--distributed_tls_write_endpoint=/osquery/distributed/write
--distributed_interval=60
--config_refresh=60
--disable_carver=true
--buffered_log_max=500000
--config_accelerated_refresh=60
--tls_server_certs='C:\Program files\osquery\certs\<zentralhost>.pem'`

Nothing jumping out in docker-compose web logs with exception of:

`web_1       | 2020-11-06 15:06:50,697 PID14 api ERROR APIAuthError Wrong node_key
web_1       | 2020-11-06 15:06:50,697 PID14 api_views ERROR APIAuthError Wrong node_key
web_1       | 2020-11-06 15:06:50,699 PID14 log WARNING Forbidden: /osquery/distributed/read
nginx_1     | 255.255.255.255 - - [06/Nov/2020:15:06:50 +0000] "POST /osquery/distributed/read HTTP/1.1" 403 14 "-" "osquery/4.5.1" "255.255.255.255"
web_1       | 2020-11-06 15:06:50,700 PID14 basehttp WARNING "POST /osquery/distributed/read HTTP/1.0" 403 14`

**Comment by ahmed-awadelkarim** [comment]
Addt Logging:

`I1106 15:19:41.883208  5772 tls.cpp:254] TLS/HTTPS POST request to URI: https://<zentralhost>/osquery/enroll
W1106 15:19:41.883208  5772 tls.cpp:101] Cannot read TLS server certificate(s): 'C:\Program files\osquery\certs\<zentralhost>.pem'
W1106 15:19:41.898823  5772 tls_enroll.cpp:77] Failed enrollment request to https://<zentralhost>/osquery/enroll (Request error: certificate verify failed) retrying...
I1106 15:19:42.914499  1832 impl_thrift.cpp:349] Thrift: Client connected.`

Any idea why the cert errors?

**Comment by ahmed-awadelkarim** [comment]
`W1106 15:28:33.395503  6012 tls.cpp:101] Cannot read TLS server certificate(s): 'C:\Program files\osquery\certs\<zentralhost>.pem'
I1106 15:28:37.426793  6012 tls_enroll.cpp:70] TLSEnrollPlugin requesting a node enroll key from: https://<zentralhost>/osquery/enroll`

**Comment by np5** [comment]
So, I am guessing the cert is not at C:\Program files\osquery\certs\<zentralhost>.pem ?

**Comment by ahmed-awadelkarim** [comment]
Actually experiencing the same issue on Mac OS

**Comment by ahmed-awadelkarim** [comment]
Yes the cert is there.

**Comment by np5** [comment]
But why do you have "Cannot read TLS server certificate(s): 'C:\Program files\osquery\certs\<zentralhost>.pem'" ?

**Comment by ahmed-awadelkarim** [comment]
Not sure? Could be user permissions, they're unable to read, but the cert file exists.

**Comment by ahmed-awadelkarim** [comment]
Thats whats perplexing me.

**Comment by np5** [comment]
Please, give us some context:

Where is the server. How ist is deployed? what kind of certificates are you using on the server? Do you distribute the zentral certificates for the clients (see base.json > "api" > "distribute_tls_server_certs" yes/no/absent ?).

And you cannot just say "Actually experiencing the same issue on Mac OS" and expect us to be able to help you!

As for the windows cert. Can you open it and verify that it is the one being used by the server ? Can you verify that osquery can read this file ?

**Comment by np5** [comment]
And yes, we are not vendoring the msi. This script is my poor attempt at pointing real windows admin in the good direction for their production deployments.

**Comment by ahmed-awadelkarim** [comment]
1. My comment wasn't intended to be disrespectful, I simply was acknowledging that I was perplexed. 
2. When I say "I'm experiencing the same issue on mac" that means when I run osqueryd verbose I see it complaining about the same cert enrollment. I recognize that is vague but I think given the context it can be understood, I wasn't looking for mac support in this thread as my focus was windows, was simply making a note.
3. I'm running the zentral server via docker-compose on a VM running in AWS. And yes the enrollment is providing the certificate to the clients upon install, I see it in the install scripts, (this has worked perfectly on linux servers)

**Comment by ahmed-awadelkarim** [comment]
`  "api": {
    "tls_hostname": "https://<zentralhost>",
    "tls_server_certs": "/zentral/conf/start/docker/tls/zentral_fullchain.crt",
    "tls_server_key": "/zentral/conf/start/docker/tls/zentral.key",
    "secret": "******"
  },`

**Comment by np5** [comment]
is it a self signed cert or not ?

**Comment by ahmed-awadelkarim** [comment]
No they're not. The zentral host install is behind an ELB on AWS. Is it possible the ELB cert could be interferring?

**Comment by np5** [comment]
/zentral/conf/start/docker/tls/zentral_fullchain.crt and /zentral/conf/start/docker/tls/zentral.key contain the right info ?

**Comment by ahmed-awadelkarim** [comment]
Correct.

**Comment by np5** [comment]
Do you see the same correct certificate, with the intermediaries in the ps1 script ?

**Comment by np5** [comment]
```ps1
# tls server cert
$tls_server_certs_file = '%TLS_SERVER_CERTS_FILE%'
$tls_server_certs = @"
%TLS_SERVER_CERTS%
"@
```

**Comment by ahmed-awadelkarim** [comment]
Yes that is included in the script.
The script contains `zentral_fullchain.crt` file contents:

**Comment by ahmed-awadelkarim** [comment]
Its just strange that this works no problem on Linux, but has been an issue on Windows and Mac for me.

**Comment by ahmed-awadelkarim** [comment]
Hi! Is there anything you would suggest I look into give a try? I'm considering redoing the install and bypassing the ELB. Is there anything else you would suggest I do?

**Comment by np5** [comment]
Before I start removing the load balancer, I would verify the permissions on the file on the machine, and verify under which user osquery is running, and if this user has enough permissions to read the file.

Also, since you are using certificates that are not self-signed, I would simply remove those from the enrollment scripts and packages, by setting the [`def distribute_tls_server_certs`](https://github.com/zentralopensource/zentral/blob/930648e463008a5b97ff1affe81f8c7cf2c0a1f3/zentral/utils/osx_package.py#L232) key to `false` in the `api` section of the `base.json` configuration. This is obviously not a fix for the issue you are having, but it will probably go away.

**Comment by np5** [comment]
Any progress ?

**Comment by ahmed-awadelkarim** [comment]
Hi! @np5 I had been pulled away from this for a bit, but a few things I'd like to update on. One I switched to using self signed certs on enrollment. Unfortunately this didn't resolve the issue. I did see some comments on tls termination on load balancers for osquery tls plugins so I'm exploring a bit there but I also did a tls_dump on the osqueryd and I saw something interesting:

`https://<zentralhost>/osquery/distributed/read
{"node_key":""}`

Any reason why this may be happening?

**Comment by ahmed-awadelkarim** [comment]
This is also interesting when I try to enroll directly:

`$ curl -v -XPOST https://<zentral host>/osquery/enroll -v
*   <zentral host IP>...
* Connected to <zentral host> (<zentral host IP>) port 443 (#0)
* ALPN, offering http/1.1
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* ALPN, server did not agree to a protocol
* Server certificate: *<zentral host domain>
* Server certificate: Amazon
* Server certificate: Amazon Root CA 1
> POST /osquery/enroll HTTP/1.1
> Host: <zentral host>
> User-Agent: curl/7.70.0
> Accept: */*`

**Comment by np5** [comment]
OK, you are changing a lot of things at the same time, and not doing what was suggested. I will try to follow.

How are you using the `--tls-dump` option ? In the launch daemon configuration ?

Has the cert in /usr/local/zentral/osquery/tls_server_certs.crt bin updated to the new self signed certificates ? Can osquery read it now ?

**Comment by np5** [comment]
By the way, the correct way to debug the enrollment with curl is:

```
curl -X POST \
-d '{"host_details": {"system_info": {"hardware_serial": "SERIAL_NUMBER"}}, "enroll_secret": "ENROLL_SECRET"}' \
https://ZENTRAL_FQDN/osquery/enroll
```

Serial number can by any string. `ENROLL_SECRET` can be found at `/usr/local/zentral/osquery/enroll_secret.txt` on macOS, when the enrollment package has been installed, or in the linux enrollment script.

**Comment by ahmed-awadelkarim** [comment]
I'm making a lot of progress, and I was always using the zentral FQDN in my requests. I've been diving into the code I know exactly where my exceptions are being generated and why I have the full requests that you outlined already from my tls_dump flag I added. 

The problem is zentral is unable to generate a machine snapshot for my windows PC, and because of that its not generating the nodekey. I don't know why its unable to generate the snapshot but I've been diving into the code to figure it out:

`zentral.contrib.inventory.models.MachineSnapshot.DoesNotExist: MachineSnapshot matching query does not exist.`

**Comment by ahmed-awadelkarim** [comment]
`zentral.contrib.inventory.models.DebPackage.DoesNotExist: DebPackage matching query does not exist.` This exception is showing up as well.

**Comment by np5** [comment]
So, the TLS errors are gone, and now you are getting errors when enrolling osquery on a windows machine ? With the enrollment script?

**Comment by ahmed-awadelkarim** [comment]
The tls errors are still there, but I think they're misleading and not what I'm focused on resolving right now. When I reran osquery with --tls_dump flag I identified this missing node key, and that was the main difference btw what I was seeing with Windows/Mac and my linux machines which enroll/enrolled fine. When I ran the curl command above directly I added the -k flag to bypass tls errors I was still seeing 403s on the client and server side, with the server side showing the exceptions I outlined above (which I had been receiving this whole time).

So point being this is a machine snapshotting issue, which I'm not trying to understand what exactly that means.

**Comment by ahmed-awadelkarim** [comment]
Are there any system reqs you're aware of?

For example as part of my enroll req for Mac, host details are as follows.:

`host_details":{"os_version":{"arch":"x86_64","build":"18G6032","major":"10","minor":"14","name":"Mac OS X","patch":"6","platform":"darwin","platform_like":"darwin","version":"10.14.6"},"osquery_info":{"build_distro":"10.12","build_platform":"darwin`

Is this version for my MAC later than supported?

`def macos_version_from_build(build):
    match = MACOS_BUILD_RE.match(build)
    if match:
        minor = int(match.group("minor")) - 4
        if minor < 8:
            # the patch letters are not always consecutive for older versions
            # probably because of the different architectures.
            raise ValueError("Cannot parse build str for macos < 10.8")
        if minor < 12:
            name = "OS X"
        else:
            name = "macOS"
        if minor >= 16:
            major = 11
            minor -= 16
        else:
            major = 10
        patch = ord(match.group("patch_letter")) - 65
        return {
            "name": name,
            "major": major,
            "minor": minor,
            "patch": patch,
            "build": build
        }
    else:
        raise ValueError("Bad build number")`

**Comment by np5** [comment]
I cannot follow you.

Are you testing on macOS or windows ? With the curl command I provided or directly with osquery ? Have installed the macOS package or the windows script ? Do you have on macOS the self-signed certificate in `/usr/local/zentral/tls_server_certs.crt` or on windows the same certs in the `C:\Program files\osquery\certs\` file ?

**Comment by ahmed-awadelkarim** [comment]
Its the same problem on both Windows/Mac and I'm going back and forth btw the two:

`:{"os_version":{"arch":"64-bit","build":"17763","codename":"Microsoft Windows Server 2
019 Datacenter","install_date":"1604664893","major":"10","minor":"0","name":"Microsoft Windows Server 2019 Datacenter","platform":"windows","platform_like":"windows","version":"10.0.17763"},`

I'm trying to explain this to you. You keep bringing up certs and I'm explaining to you this isn't a cert issue. It's a misleading error message thats coming from osquery tls plugin. If it was really a cert issue the Linux hosts would fail to enroll, and when I run the enroll command manually with the `-k` flag then enrollment would succeed but it doesn't. 

This has to do with machine snapshots in the Zentral code. Are you familiar with them? Do you know who is? Have you gotten this to work in the past? If so, what Windows or Mac distros were you using?

**Comment by ahmed-awadelkarim** [comment]
To be more specific, are you familiar with how the node_key gets generated, and why it would come back blank in some cases?

**Comment by np5** [comment]
Did you get an empty node key with the curl test I suggested ?

**Comment by ahmed-awadelkarim** [comment]
I figured this out. I got this working by creating a new Business Unit and new osquery configs for each mac and windows hosts. Bypassing the startup script and running the enrollment command manually.

**Comment by ahmed-awadelkarim** [comment]
I got the node key for both hosts in this case and was then the hosts showed up in the Zentral UI.

**Comment by np5** [comment]
Bypassing all your issues, and manually hacking a solution is not the way Zentral is supposed to work or be used. It is not good engineering practice too. You haven't clearly demonstrated either the existence of an issue or helped us toward a solution. Please take a breath and review your posts in this thread, you will see.

I will close this now. It has been a massive waste of time.

**Comment by ahmed-awadelkarim** [comment]
With all due respect; you have wasted my time tremendously. The documentation is out of date and/or nonexistent. You were rude and lecturing from the beginning and offered nothing close to "expertise" . I was able to figure this out in spite of you and not because of your support in anyway. I hope one day you learn how to deal with humans and realize that communication is huge part of being an engineer and so is a 12+ year old maturity level.

Not only that, you seem to have no idea how osquery even works, or the underlying tools you support, so go ahead and do some more research in the future.

**Comment by ahmed-awadelkarim** [comment]
Also @np5 I resolved this, and your enrollment script has a bug/is missing and important step which caused the cert errors.
