### ISSUE TITLE
Enhancement: Manifest names are not editable

### ISSUE THREAD

**Issue by arubdesu** [zentralopensource/zentral#118]
Several other labels can be modified, but Manifests cannot currently. (This is when sysadmins who think they're smart would tinker with the database, which nobody wants 😅)

**Comment by np5** [comment]
🔥 There is a [one-to-one](https://github.com/zentralopensource/zentral/blob/c71a4470ee1d908008620bd9e36e3a84db8a63cb/zentral/contrib/monolith/models.py#L463) relationship between the `Manifest` and the `MetaBusinessUnit` and the name of the manifest is the name of the business unit.
