### ISSUE TITLE
Santa sync with Zentral fails - 400 bad request

### ISSUE THREAD

**Issue by aivarastcloud** [zentralopensource/zentral#141]
Santa sync with Zentral server using config generated in Zentral server fails with erro 400 bad request.
Configuration file was generated in Zentral website and then installed in MAC.
It is possible that there are issue with enrollment, but not much documentation found of working configuration.
![zentral-santa](https://user-images.githubusercontent.com/76938215/103513814-0b701600-4e74-11eb-8fed-8539a4cbc349.png)

**Comment by np5** [comment]
We need the zentral version/commit, and the santa version to investigate further.

**Comment by aivarastcloud** [comment]
Zentral version - v0.7.0-beta.0
Santa version - v1.17

**Comment by np5** [comment]
See last [breaking change](https://github.com/google/santa/commit/c5a048f4d9d9a421417f72a11f90e1e40970ad6f) made by Santa in v1.17.

We have fixed this issue with f4d0c7c. There is also a [new Santa configuration option](https://github.com/google/santa/commit/01e4e15b81a30c84eeae15f1a380876d2e6ffbd7) `EnableBackwardsCompatibleContentEncoding`.

Either use the master version of Zentral, or use the Santa configuration option, that should fix the issue.

**Comment by aivarastcloud** [comment]
I have tested with older Santa v1.15 and it works, so yes you are correct it is due to encoding.
I am not quite sure how to enable this Santa Configuration option in new v1.17 to be honest.. I am just deploying Santa using .dmg file and how can I pass the different configuration option?
Also what do you mean :deploy master version of Zentral"
P.S. Thank you for your help pointing to the issue, these additional questions can be ignored if you have no time. I am fine to close this issue.

**Comment by headmin** [comment]
@aivarastcloud 

to use the Santa configuration option =>

add the following to the `.plist` or `.mobileconfig` that works with Santa 1.15 and its should work with Santa 1.17 release

```
	<key>EnableBackwardsCompatibleContentEncoding</key>
	<true/>

```
source: https://github.com/google/santa/releases/tag/1.17


to deploy master version of Zentral =>

this refer to deploy the main branch from the GitHub repository. i.e. with ZAIO this is simply run the tool build for the purpose
 
```
sudo /home/zentral/app/utils/deploy.py
```
source: https://zentral.readthedocs.io/en/latest/deployment/zaio-setup/

**Comment by aivarastcloud** [comment]
Thank you for all the help, really appreciated. I will close the issue now.
