### ISSUE TITLE
osquery enrollment package installs "/Library/LaunchDaemons/com.facebook.osqueryd.plist" with invalid permissions.

### ISSUE THREAD

**Issue by goobersmooch** [zentralopensource/zentral#18]
The current osquery enrollment package installs the "/Library/LaunchDaemons/com.facebook.osqueryd.plist" file with invalid permissions. This causes launchctl to fail to load "/Library/LaunchDaemons/com.facebook.osqueryd.plist" also causing the following error message in the system log: Caller specified a plist with bad ownership/permissions: path = /Library/LaunchDaemons/com.facebook.osqueryd.plist, caller = launchctl.89355.

I submitted #16 to fix the problem, but I was told it would be better to open an issue so that we can find the root of the cause.

**Comment by headmin** [comment]
I guess you'll run a docker based setup right ?

If so what do you get as result from the web container :
 
`sudo docker exec -ti zentral_web_1 ls -al /zentral/zentral/contrib/osquery/osx_package/build.tmpl/root/Library/LaunchDaemons/com.facebook.osqueryd.plist`

Also how does the permissions look in the local repo you've started docker-compose from ?

**Comment by goobersmooch** [comment]
sudo docker exec -ti zentral_web_1 ls -al /zentral/zentral/contrib/osquery/osx_package/build.tmpl/root/Library/LaunchDaemons/com.facebook.osqueryd.plist outputs -rw-rw-r--

localAdmin@Zentral:~/zentral$ ls -l ~/zentral/
total 64
-rw-rw-r-- 1 localAdmin localAdmin   310 Oct 12 11:34 basic-auth-use-info.md
drwxrwxr-x 4 localAdmin localAdmin  4096 Oct 12 11:34 conf
-rwxrwxr-x 1 localAdmin localAdmin  1459 Oct 12 11:34 docker-compose-basic-auth.yml
-rw-rw-r-- 1 localAdmin localAdmin  1402 Oct 12 11:34 docker-compose.yml
-rwxrwxr-x 1 localAdmin localAdmin  2484 Oct 12 11:34 docker-entrypoint.py
-rw-rw-r-- 1 localAdmin localAdmin   971 Oct 12 11:34 Dockerfile
drwxrwxr-x 2 localAdmin localAdmin  4096 Oct 12 11:34 docs
-rw-rw-r-- 1 localAdmin localAdmin 11358 Oct 12 11:34 LICENSE
-rw-rw-r-- 1 localAdmin localAdmin   265 Oct 12 11:34 README.md
-rw-rw-r-- 1 localAdmin localAdmin   178 Oct 12 11:34 requirements.txt
drwxrwxr-x 7 localAdmin localAdmin  4096 Oct 12 11:34 server
drwxrwxr-x 5 localAdmin localAdmin  4096 Oct 12 11:34 tests
-rw-rw-r-- 1 localAdmin localAdmin    58 Oct 12 11:34 tox.ini
drwxrwxr-x 7 localAdmin localAdmin  4096 Oct 12 11:34 zentral

**Comment by headmin** [comment]
That very much depends on your docker host environment. The umask should be 0022, you have umask 0002 probably because  you have set  **USERGROUPS_ENAB = yes** by default in `/etc/login.defs` (ie. setting in Ubuntu). You could change that or alternatively just set a `umask 0022`  in Terminal before checking out via git.

**Comment by goobersmooch** [comment]
I just looked and indeed I do have USERGROUPS_ENAB = yes in /etc/login.defs. Is this a default setting in Ubuntu 16.04?

**Comment by np5** [comment]
It is a default settings in Ubuntu, yes.

**Comment by goobersmooch** [comment]
Okay. So I guess in my case the root of the problem is **USERGROUPS_ENAB = yes** being set in `/etc/login.defs`.

**Comment by goobersmooch** [comment]
After further investigation and much help from Henry @headmin  and @np5 , the root of the cause was not setting the `umask` before checking out the project from github. To resolve this, run `umask 0022` just before doing a git checkout.
