### ISSUE TITLE
Workers do not auto-reconnect with the Database

### ISSUE THREAD

**Issue by np5** [zentralopensource/zentral#184]

**Comment by arubdesu** [comment]
For clarification, the symptom experienced was after e.g. AWS database changes (like maintenance that upgraded the engine on the RDS host) workers would not resume processing events. Temporary manual intervention was to replace/refresh the ~horse~ worker instance(s).

**Comment by np5** [comment]
It seems to work now. At least for your deployment with AWS SNS/SQS queues. Can we close it?

**Comment by arubdesu** [comment]
Yes, confirmed good
