### ISSUE TITLE
elasticsearch/'actions' button accessible from machine

### ISSUE THREAD

**Issue by arubdesu** [zentralopensource/zentral#221]
As auth to kibana is likely to get separated from only proxied by zentral, RBAC restricting the link for a machine events from its main details page (or the machine-specific events page) should result in removing that Elasticsearch button entirely. Likewise with nothing available from the Actions button it should not be visible in the interface, to avoid this:
![image](https://user-images.githubusercontent.com/388808/111441022-403cfb00-874a-11eb-8a0e-e7934b5040e9.png)

**Comment by np5** [comment]
add the `events_url_authorized_groups` key in each store config:

Example:

```json
{"stores": {
    "elasticsearch": {
      "frontend": true,
      "backend": "zentral.core.stores.backends.elasticsearch",
      "events_url_authorized_groups": ["Test", "YOLO"],
      "hosts": [
        "http://elastic:9200"
      ],
      "index": "zentral-events",
      "kibana_base_url": "https://zaio.example.com/kibana/",
      "kibana_index_pattern_uuid": "zentral-events-index-pattern"
    }
 }}
```

If absent, all stores buttons will be displayed. If superuser too. If present, group membership will be checked.
