### ISSUE TITLE
Architecture Images broken link in wiki

### ISSUE THREAD

**Issue by JJediny** [zentralopensource/zentral#24]
https://github.com/zentralopensource/zentral/wiki#architecture

https://github.com/zentralopensource/zentral/wiki/Home/_compare/d55c1c805763e34d4d2820a17f52f6ba2eeb7963...5616c02e8c45ecb4a5f4361549463e81b091dc51#diff-b4d7124d2993cd13aabeec1fc19baf51L92

This should fix...
```
![](wiki/images/overview1.png)
![](wiki/images/overview2.png)
```

**Comment by headmin** [comment]
fixed
