### ISSUE TITLE
http_post probe action fails with "NoneType object is not callable"

### ISSUE THREAD

**Issue by sierra-hotel** [zentralopensource/zentral#279]
Hello there!

I've created a new http_post action by adding it to `base.json` like so:
```
"actions": {
    "debug": {
      "backend": "zentral.core.actions.backends.json_file",
      "local_dir": "/tmp/zentral_notifications/"
    },
    "post_to_server": {
      "backend": "zentral.core.actions.backends.http_post",
      "url": "https://<redacted>.ngrok.io/zentral",
      "headers": {
        "token": "<redacted>"
      }
    }
  }
```

It appears in the list of probe actions, but when I select it I get the following error:

```
Request Method: | GET
https://zentral/probes/1/actions/post_to_server/edit/
2.2.20
TypeError
'NoneType' object is not callable
/opt/venv/lib/python3.9/site-packages/django/views/generic/edit.py in get_form, line 33
/opt/venv/bin/python
3.9.4
['/zentral',  '/zentral',  '/zentral/server',  '/usr/local/lib/python39.zip',  '/usr/local/lib/python3.9',  '/usr/local/lib/python3.9/lib-dynload',  '/opt/venv/lib/python3.9/site-packages']
Thu, 22 Jul 2021 00:23:14 +0000
```

And the local variables for that line are:
```
form_class | None
self | <zentral.core.probes.views.EditActionView object at 0x7f94bc4df250>
```

I'm not sure if this is related, but I did notice that most of the probe action definitions have form classes set, like so:
https://github.com/zentralopensource/zentral/blob/0c5896ece1388131e84c2d6e0ee19f5aec7e7faa/zentral/core/actions/backends/email.py#L11

But the http_post.py just has it hard-coded to None:
https://github.com/zentralopensource/zentral/blob/0c5896ece1388131e84c2d6e0ee19f5aec7e7faa/zentral/core/actions/backends/http_post.py#L7

Please let me know what the fix to this might be!
Thanks,
Seán

**Comment by np5** [comment]
This should work better now. Thanks for your help fixing this issue.

**Comment by sierra-hotel** [comment]
Thanks for the lightning fast turnaround time @np5 !
