### ISSUE TITLE
zentral logging: file, syslog?

### ISSUE THREAD

**Issue by juju4** [zentralopensource/zentral#28]
Is there a way to get received logs (osquery, santa...) into a file on zentral server or into standard syslog?

Thanks

**Comment by np5** [comment]
Not possible at the moment. What is the use case ?

**Comment by juju4** [comment]
Typical use case for syslog is integration in SIEM or a more global logging platform.
It could be ELK or not. syslog (especially rsyslog with tcp+tls) gives more option.

file output is mostly for debug or to simplify architecture if don't want ELK and the rest.

**Comment by np5** [comment]
The structure of the events can vary a lot. Osquery, especially with the distributed queries, can generate a lot of information for example. And this information is totally different from the information sent by Santa.

I have some questions:

* Would you like to get a summary of the event sent to a third party application or the whole information ?
* How would you like to serialize the information in a syslog message (the tuples sent by osquery, the actions taken by santa) ?
* Would you like to send all the events or just some of them ?

There are two ways of attacking this problem, depending on your answers. Either an [Event Store](https://github.com/zentralopensource/zentral/tree/master/zentral/core/stores/backends) or an Action like [this one](https://github.com/zentralopensource/zentral/blob/master/zentral/core/actions/backends/json_file.py) that write one file per event for debugging.

**Comment by juju4** [comment]
Event as is
especially for osquery, be it daemon activity or json results, both can end in a syslog format directly with the daemon (filesystem or syslog) so want to keep this in a centralize mode.

1. raw/whole event
2. raw json
3. all.

**Comment by np5** [comment]
I have just pushed a new syslog event store. It will send all events to a syslog server.

It can not be used as a "frontend" (aka primary) store because zentral needs a store that supports queries (for the machine events, the probe events), but it should be enough to ship the events somewhere else.

You can configure it along an elasticsearch store, like in [this example](https://github.com/zentralopensource/zentral/blob/195ce29d3bd8720b3745ee0c3196a3ab0736f6e9/conf/syslog/zentral/base.json#L41). Defaults are protocol: UDP, port: 514, facility: user, priority: info.

I could add TLS and the rfc5424 support if needed.

**Comment by juju4** [comment]
Thanks a lot @np5! will try to test this weekend.
Normally that should be enough for me.
Adding more would be useful even if I think, once the logs are in zentral, you are already in a "restricted" network zone. Depends on you.

**Comment by jonflaire** [comment]
@juju4 did you have any luck in getting osquery out to syslog via zentral?

**Comment by headmin** [comment]
it will works fine to output all  (not only osquery) zentral stored events to ext. syslog store. details have to be configured in base.json - have you tried that out ?

**Comment by juju4** [comment]
for now, my setup has only direct syslog from osquery. built and unbuilt my zentral and for now, unbuilt.
Try zentral syslog store. It's in my plan but no time currently.
