### ISSUE TITLE
Adding TOTP to a local user repeatedly fails 

### ISSUE THREAD

**Issue by arubdesu** [zentralopensource/zentral#301]
Hitting return or clicking the save button while adding TOTP to a local user continually fails. After 3 tries we were able to save it, but experienced the same issue in a separate staging instance.
Big Sur recent with Chrome recent, multiple authentication apps, confirmed time was accurate-looking on web instance(s).

**Comment by arubdesu** [comment]
We understand that hitting return while inputting the code the first time (instead of clicking the button) recycles the secret/QR code instead of entering it, but that seems unintuitive as well, should we spin up a separate issue for that?

**Comment by arubdesu** [comment]
Confirmed working good for me in staging with 1password as the TOTP device, asking @boycycle to confirm as well

**Comment by boycycle** [comment]
Issue still occurring for me. Staging took 2 attempts to add to DUO mobile. Prod still failing after 2 attempts.

**Comment by np5** [comment]
Can you confirm that the QR code stays the same in your staging environment and doesn't change at each attempt anymore ? I do not know the state of your production environment, but I know that the staging environment is up to date.

Also, can you try enrolling with a different app, like google authenticator? Try to see as well if the google authenticator codes are changing at the same time as the duo codes.

**Comment by boycycle** [comment]
Issue is related to DUO mobile app only, it is ok to close this issue, thanks!

**Comment by np5** [comment]
Merci!
