### ISSUE TITLE
Issue with Santa combined enrollment and installer

### ISSUE THREAD

**Issue by zbuc** [zentralopensource/zentral#31]
If I use the Santa installer with enrollment and Santa installation combined, there seems to be a problem where the `/var/db/santa/config.plist` file does not have the `MachineID` set correctly.

This issue does *not* happen if I use the enrollment-only pkg.

The plist file winds up containing the following:

```
...
	<key>MachineID</key>
	<string>%MACHINE_ID%</string>
...
```

I repackaged the installer and set `#!/usr/bin/sh -x` in the shebang for the `postinstall` script and verified that it is running the `sed` replacement. Also, the `postinstall` script's `sync` works fine, but when I try to sync after installation it obviously fails because of the bad `MachineID`.

**Comment by np5** [comment]
Thanks for reporting this issue. Closed by 02b6da81a5973a29db10261d0a16cf4dcc8bf099.
