### ISSUE TITLE
osquery enrollment package download fails when including a pre-release build of osquery

### ISSUE THREAD

**Issue by samuarl** [zentralopensource/zentral#32]
Attempting to bundle an osquery release with an enrolment package fails if the bundled osquery version is pre-release.

The package builder gets all the available release versions from the github API which includes pre-release versions. It then assumes the corresponding S3 download URL, but this does not work for pre-release builds.

Instead the S3 AccessDenied XML response is downloaded and saved to `osquery-2.4.3.pkg` which then causes the error below.

> Exception Type:	CalledProcessError
> Exception Value:	Command '['/usr/local/bin/xar', '-x', '-C', '/tmp/tmpt3by6q2hzentral.utils.osx_package', '-f', '/tmp/osquery/releases/osquery-2.4.3.pkg']' returned non-zero exit status 1

**Comment by samuarl** [comment]
It would be nice to be able to bundle pre-release builds for testing, though I suspect it's probably easiest to just filter out pre-release versions from the github API response, unless pre-release builds can be fetched from S3 with some other url format?

**Comment by samuarl** [comment]
Actually there are releases tagged as prerelease in the github API that have working downloads on the osquery S3 bucket, so it may be better to detect the invalid download URL and warn there is no package for that build yet.

**Comment by np5** [comment]
This should fix the issue. I don't want to check all the links while building the form. It is already slow enough!

Don't forget to remove the osquery package file in your container. It might exist and contain the S3 xml error message.

Thanks for reporting this issue.
