### ISSUE TITLE
Can't get syslog output working

### ISSUE THREAD

**Issue by spbkaizo** [zentralopensource/zentral#323]
Hi,

Struggling to forward events to a syslog host, edited the config at https://github.com/zentralopensource/zentral/blob/38ff843d538cf55122834e52c9226a385557e4d9/conf/syslog/zentral/base.json#L45

and changed that to reference an actual host, as well as added a port.  For clarity, here's what my running config looks like:

```
  "syslog": {
      "backend": "zentral.core.stores.backends.syslog",
      "host": "10.1.1.1",
      "port": "1514",
      "protocol": "tcp"
    }
```

I've confirmed connectivity to the host from a docker container running on the host, plus zentral itself is able to connect outbound (e.g. when building osquery packages) so pretty sure it's not that.

Am I missing something from this config that triggers it?

**Comment by np5** [comment]
Is the corresponding store worker up and running ? What is your configuration (VM/container/container management) ?

**Comment by spbkaizo** [comment]
Config is on a host using docker-compose, I don't currently have a syslog worker image running - I note there is a compose file for one which leverages syslog-ng (by default, writing to stdout).  

So the correct approach is to deploy this container, then use the syslog-ng.conf file to customise the output to where I wish?

**Comment by np5** [comment]
The syslog output is for when you already have a Syslog sink where you want to send some Zentral events. In that case, add the syslog store to the base.json config currently used (by default conf/start/zentral/base.json) and restart the workers container. A new store worker will be forked and will start sending the events. To monitor this: `docker compose logs -f --tail=100 workers`.

If you do not have a syslog sink, yes, you can test the syslog forwarding using the extra docker-compose configuration with the syslog-ng container. But you do not need the syslog-ng server/container, if you already have a syslog sink.

Those docker-compose setups are only used for development and testing. Solid production deployments require a bit more work, with DB backups, event processing capacity planing, event storage capacity planing, monitoring, zentral upgrades, system security upgrades, …

**Comment by np5** [comment]
If you have an event store not yet supported by Zentral, and using syslog only as transport, please tell us, and we will consider implementing a module for it. The syslog transport is "lo-fi", because of the marshalling constraints.

**Comment by spbkaizo** [comment]
Our goal is to send events across to a Graylog server.  This will ingest events in many formats (with syslog being the lowest common denominator).

It would be excellent if you can use this as an event store in a more native fashion, e.g. GELF or similar (https://docs.graylog.org/docs/gelf)

**Comment by np5** [comment]
What kind of transport is the most common one ? HTTP ? TCP ?

**Comment by janheise** [comment]
@spbkaizo can you be a bit more specific about your configuration? syslog usually listens on port 514, you wrote 1514 - on what port did you configure the graylog syslog ingestion (the examples in the docs are using 514)? Did you configure TLS?

**Comment by spbkaizo** [comment]
@janheise We're using a solution called graylog as a SIEM, which has a multitude of mechanisms to ingest 'messages'.  One of these is a syslog 'catch-all' ingest method.

This listener is running on 1514, for reasons that the listener needs to be on a port >1024 otherwise it requires root permissions which we're trying to avoid.  It's listening on TCP, but with no TLS.  I can do some testing using UDP and see what happens....

@np5 I'm not sure there is a common transport across the graylog userbase - we're currently using CEF and syslog ingestion.  Thinking about it CEF might give you the best bang for your development time, with it then being useful across a multitude of SIEM solutions and similar applications.  GELF is probably too niche to warrant any effort until afterwards, if you chose to do that also.

**Comment by np5** [comment]
The problem is not really the format. GELF or CEF marshalling is relatively easy. The problem is how to best present the data for the event stores.

For example, some event store have a predefined and reserved field for the ip address, or the user agent. In that case, we like to marshal the zentral events so that the event store will pick up those fields.

But with graylog, I cannot really see a common schema. And if you are using it as a SIEM, there must be one, otherwise it would be impossible to track an IP address for example across events coming from different sources.

**Comment by spbkaizo** [comment]
So this would be the next stage, we'd have to create extractors that can parse the data that comes across to Graylog.  For example, here's a definition for Apache logs : https://github.com/kevXZY/graylog/blob/master/apache_extractors.json

**Comment by janheise** [comment]
@spbkaizo I'm currently doing some work for graylog and do personally know the zentral guys. That's why I think there might be just a simple misunderstanding or config error. I did not try to connect zentral to graylog but will give it a try.

**Comment by np5** [comment]
@spbkaizo Since we have to marshal each zentral event anyway to send them to graylog, we could do the heavy lifting, and use extra fields for the common zentral event metadata at index time (user agent, ip, user?, event type, …).

**Comment by np5** [comment]
So, I have just tested the docker compose syslog config, and it works.

First, to make things easier, and not mess up your current setup, create an alias, and use a specific project name.

`alias dcsys='docker compose -p ztlsys -f docker-compose.yml -f docker-compose.syslog.yml'`

Then bring everything up:

`dcsys up -d`

Once everything is up, log into the web container for example, and create a superuser:

```
dcsys exec web bash
python server/manage.py create_zentral_user --superuser username user@example.com
```

Follow the password reset link, and set the password. You can then login.

To tail the syslog container output:

`dcsys logs -f --tail=100  syslog`

If you change the store configuration (in `./conf/syslog/zentral/base.json` for this setup), you need to restart the workers container.

`dcsys restart workers`

Then

`dcsys logs -f --tail=100 workers` to tail the workers container logs.

**Comment by janheise** [comment]
@spbkaizo did you check the null delimiter setting in the config for the tcp-input
![Screenshot from 2021-11-23 17-41-31](https://user-images.githubusercontent.com/1190735/143066711-cc33bbe7-2198-40ae-b08f-9a62416de17a.png)
?

**Comment by spbkaizo** [comment]
Hi @janheise sorry - yes that's on and I apologise for confusion - the issue was that the syslog container wasn't running, and the fix for me was to run the compose file including the syslog component:

`docker-compose -f docker-compose.yml -f docker-compose.syslog.yml up`

After that behaviour is as expected.  The aspect I'm still unclear on is clarity on if this is what a user is supposed to run in order to have this functionality, or if the container should have been automatically instantiated by something else and wasn't.  Again though, as @np5 pointed out here https://github.com/zentralopensource/zentral/issues/323#issuecomment-976441251 running the solution via docker-compose is only intended for dev/test purposes, so this is more a 'me' problem :-)

Thanks for the support.

(I'm happy for this to be closed now if you wish)

**Comment by np5** [comment]
The syslog container not running cannot be the issue. It is not configured to forward the logs. It is only included to see if the zentral syslog shipping works.

What probably happened, is that when including the extra `docker-compose.syslog.yml`, you activated the `./conf/syslog/zentral/base.json` instead of the `./conf/start/zentral/base.json` configuration. See:

https://github.com/zentralopensource/zentral/blob/38ff843d538cf55122834e52c9226a385557e4d9/docker-compose.syslog.yml#L8

You could have achieved the same result by adding a syslog store to the `./conf/syslog/zentral/base.json` configuration.

https://github.com/zentralopensource/zentral/blob/38ff843d538cf55122834e52c9226a385557e4d9/conf/start/zentral/base.json#L28-L37

vs

https://github.com/zentralopensource/zentral/blob/38ff843d538cf55122834e52c9226a385557e4d9/conf/syslog/zentral/base.json#L34-L48

Do not forget to restart the workers container when you change the configuration.

If you need a more robust test setup, we can provide a Zentral instance in AWS or GCP for 15 days. Contact us at https://zentral.pro.
