### ISSUE TITLE
Rename Osquery distributed query probe to Osquery adhoc query probe

### ISSUE THREAD

**Issue by headmin** [zentralopensource/zentral#35]
follow change from osquery project https://github.com/facebook/osquery/issues/3057

**Comment by theopolis** [comment]
Hey @headmin, the current recommendations are to rename to "live" instead of "adhoc". We'll be exploring this soon. And will give you a heads up.

**Comment by headmin** [comment]
Hey @theopolis, thanks for the info!

**Comment by np5** [comment]
Called "Run" in Zentral since b24befcfe1f092944a4c7f7d4c4c4d122433e70f. Still called DistributedQuery in the models. Reason: in Zentral, the same Query object can be scheduled in a Pack, or "Run" as a distributed query.
