### ISSUE TITLE
Check if JSS API is disabled

### ISSUE THREAD

**Issue by macmule** [zentralopensource/zentral#37]
Not sure _how_ you'd test for this.

But set up a new JSS instance, scratched my head as to why Zentral seemed happy but no data. Turns out the API was disabled.

**Comment by np5** [comment]
You mean that it is annoying that we don't show an error message when you create the jamf instance, and that we only show the message where you click on the setup button ?

**Comment by macmule** [comment]
Well.. setup showed successful.. but the /api endpoint was removed.. so actually wasn't successful

**Comment by chrishumphries** [comment]
Yes, when using jamfcloud, what should the port and api endpoint be? No matter what I enter, it does not connect to Jamf.
