### ISSUE TITLE
Munki enrollment - problem

### ISSUE THREAD

**Issue by djordjezunic** [zentralopensource/zentral#42]
Hi,

Is anyone having problem with enrollment of Munki software on client computer with Zentral?

When i run "zentral_munki_enroll.pkg" installer on Mac OS X 10.12.5 it passes without any problem, more correctly it does not show any problem in GUI interface, but it does not install application on computer. 

In log file i have found following, looks link that it's missing '/Library/Managed Installs/ApplicationInventory.plist' file.

Jun 12 12:07:17 Djordje-Test-Mac-mini installd[388]: PackageKit: Executing script "./postinstall" in /private/tmp/PKInstallSandbox.oaxLzJ/Scripts/io.zentral.munki_enroll.bu_5aa68de8.J5qcgC
Jun 12 12:07:22 Djordje-Test-Mac-mini installd[388]: ./postinstall: Traceback (most recent call last):
Jun 12 12:07:22 Djordje-Test-Mac-mini installd[388]: ./postinstall:   File "/usr/local/zentral/munki/zentral_postflight", line 325, in <module>
Jun 12 12:07:22 Djordje-Test-Mac-mini installd[388]: ./postinstall:     ai = ApplicationInventory()
Jun 12 12:07:22 Djordje-Test-Mac-mini installd[388]: ./postinstall:   File "/usr/local/zentral/munki/zentral_postflight", line 111, in __init__
Jun 12 12:07:22 Djordje-Test-Mac-mini installd[388]: ./postinstall:     self.data = plistlib.readPlist(self.APPLICATION_INVENTORY)
Jun 12 12:07:22 Djordje-Test-Mac-mini installd[388]: ./postinstall:   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 75, in readPlist
Jun 12 12:07:22 Djordje-Test-Mac-mini installd[388]: ./postinstall:     pathOrFile = open(pathOrFile)
Jun 12 12:07:22 Djordje-Test-Mac-mini installd[388]: ./postinstall: IOError: [Errno 2] No such file or directory: '/Library/Managed Installs/ApplicationInventory.plist'
Jun 12 12:07:22 Djordje-Test-Mac-mini installd[388]: PackageKit: Writing receipt for io.zentral.munki_enroll.bu_5aa68de8 to /
Jun 12 12:07:22 Djordje-Test-Mac-mini installd[388]: Installed "zentral_munki_enroll" ()

**Comment by headmin** [comment]
Question: 
So you do you have Munki 3 already installed on the system ?

**Comment by headmin** [comment]
The *zentral_munki_enroll.pkg* require your Munki  must already installed  and running well with the munki repo on the client. We just ship events and inventory info from Munki on the client to your Zentral instance.

**Comment by np5** [comment]
I have just pushed a commit that fixed the issue when ApplicationInventory.plist is missing. The postinstall script will exit with a status code > 0 in case of an error as well.

**Comment by djordjezunic** [comment]
Sorry i didn't know that i need to have Munki installed on client computer.
After Munki set up everything went ok.

Thank you :)
