### ISSUE TITLE
Can't create OSQuery "snapshot" queries

### ISSUE THREAD

**Issue by zbuc** [zentralopensource/zentral#44]
Currently it doesn't seem like you can create snapshot queries with Zentral:

https://github.com/zentralopensource/zentral/blob/20b293c73dd4a20a87d755554f683cdafb0aca2c/zentral/contrib/osquery/probes/base.py#L108

Snapshot queries would be a useful configuration option (OSQuery docs):

> Snapshot queries, those with snapshot: true will not store differentials and will not emulate an event stream. Snapshots always return the entire results from the query on the given interval. See the next section on logging for examples of each log output.

**Comment by np5** [comment]
Resolved by 981174de1b45a
