### ISSUE TITLE
Zentral packer installation for Linux/CentOS

### ISSUE THREAD

**Issue by erdarun** [zentralopensource/zentral#45]
I'm looking for steps to setup Zentral all in one on Linux/CentOS.

Also If there are any steps already documented for installing Zentral seperately and it's dependent modules like Postgres, ElasticSearch on different nodes instead of Docker/AWS/GC/Vagrant/OVA will be helpful.

**Comment by headmin** [comment]
we have internally used RHEL 7.3 with Zentral-all-in-one w/ packer. 
What scaling you have in mind w/ different nodes ? can you explain your purpose in more detail ?

**Comment by erdarun** [comment]
@headmin Oh that's cool.

Basically we have 2 DC's, 1 DC with 4 machines so totally 8 machines for production deployment.

We are looking to distribute zentral and it's dependent modules across each DC so that end goal is loadbalancing between DC's and even if 1 DC goes down other should support incoming traffic. 

We are planning to make Zentral Active-Active across DC.

Please let me know for more information if required.

Also regarding RHEL 7.3 Zentral-all-in-one packer, Can we get hold of packer and is it ready for production deployment and installation steps would be very helpful.

Thanks.
