### ISSUE TITLE
Docker swarm cluster - Postgres DB duplicate key value violates unique constraint "inventory_machinesnapshotcommit_serial_number_f9fee8fa_uniq"

### ISSUE THREAD

**Issue by erdarun** [zentralopensource/zentral#48]
Hi,

We have split up zentral components using docker swarm version 17.06.

We have deployed Zentral Web, Workers, RabbittMQ, Nginx in 2 machines, Elastic search cluster created with 4 nodes, Kibana/Prometheus/Postgres db running in seperate instance.

Elastic search cluster and Postgres db data has been mapped to a shared drive in all machines.

Setup has been running fine where we have already enrolled 50 machines. We can see event logs received from existing enrolled machines.

But now when we tried enrolling new machines through osquery tls plugin "enroll" it gives 200 HTTP response but machine not added to Inventory machines list as checked from zentral web. No help from application logs as there are no errors logged.

osquery tls plugin can pull "configs" from zentral also "log" api returns 200 response. Even then there is no machine enrolled or logs in zentral web/elastic search.

We are not sure why zentral gives 200 HTTP response but data not getting saved. 

Need help to identify which zentral component is failing. We are planning to scale for nearly 1500-2000 machines.

**Comment by np5** [comment]
Hi,

1. Check the content of `/usr/local/zentral/osquery/enroll_secret.txt` on the machine that you are trying to enroll. See if the serial number is correct and not shared by another machine in your fleet.

2. You could build an event probe to see if the enrollment events are saved by Zentral, and with which machine there are associated.

**Comment by erdarun** [comment]
Hi np5,

1. enroll_secret.txt has the right serial number not shared by other fleet. Zentral gives 200 response for enroll but doesn't show up under Inventory machines list.

2. We are using zentral for FIM events reporting so we hav created FIM probes for list of files to be monitored which are mapped to particular business unit. We are seeing osquery events for existing enrolled machines of same business unit but new machine enrolled and logs posted from osquery daemon received 200 response not getting listed in zentral web so can't view event logs.

**Comment by np5** [comment]
I defensively decided to catch the postgres error in the code, in case there was a race to save the same inventory data. See [here](https://github.com/zentralopensource/zentral/blob/095cfc774af4a7259c8b6816d0a454557cc81641/zentral/contrib/inventory/models.py#L468). At the time, I did not think it could happen, but apparently it does. Could you tell me how often you see those lines ?

About the "Connection reset by peer", it depends on your docker startup script, the connections between the different containers and the db…

**Comment by erdarun** [comment]
Zentral has been running for past 4 days.

'Connection reset by peer' has been observed twice sometime after service startup on the same day.

Duplicate key violates for serial number '0123456789' has been observed many times more than 10 times in past 4 days.

**Comment by np5** [comment]
Hi,

This serial number looks like the one used by the dummy inventory module. You should deactivate it. But before you do it, could you tell me how many Zentral workers you have, filter the inventory events for this "machine", and find the rate at which they are coming ?

**Comment by erdarun** [comment]
Hi @np5 

How to deactivate dummy inventory modules "0123456789","9876543210"? Archive existing enrolled machines?

I have 2 instances of zentral workers running. Rate is 2 events per minute.

**Comment by np5** [comment]
Hi,

If you archive the machines, they will come back, because the dummy inventory client is going to simulate update events.

Edit `base.json` and remove the dummy client:

```json
"zentral.contrib.inventory": {
  "prometheus_bearer_token": "CHANGE ME!!!",
  "clients": [
    {
      "backend": "zentral.contrib.inventory.clients.dummy"
    }
  ]
}
```

Then you can archive the machines.

**Comment by erdarun** [comment]
Hi @np5 

Thanks.

Is there a way in zentral where we can create multiple file paths in probes? We have requirement for 3000 file paths per probe so manually creating 1 by 1 is time consuming

**Comment by np5** [comment]
I would advice you to generate a JSON probe feed based on a simple and editable input containing the 3000 paths. This JSON probe feed can then be imported in Zentral. You can even update the probe after you have updated the feed.

**Comment by erdarun** [comment]
Hi @np5 

Do we have an example for valid JSON probe feed with an expected structure and it should be imported under which option under zentral?

**Comment by erdarun** [comment]
Hi @np5 

We are seeing RabbitMQ error below, So it's not storing logs to elasticsearch but we can see lot of osquery/log API hits with 200 from zentral web.

```
=WARNING REPORT==== 6-Sep-2017::14:54:35 ===
memory resource limit alarm set on node rabbit@07f7fa23cf2f.

**********************************************************
*** Publishers will be blocked until this alarm clears ***
**********************************************************

=INFO REPORT==== 6-Sep-2017::14:54:38 ===
vm_memory_high_watermark clear. Memory used:6341415648 allowed:6663512064

=WARNING REPORT==== 6-Sep-2017::14:54:38 ===
memory resource limit alarm cleared on node rabbit@07f7fa23cf2f

=WARNING REPORT==== 6-Sep-2017::14:54:39 ===
memory resource limit alarm cleared across the cluster

=ERROR REPORT==== 6-Sep-2017::19:06:21 ===
closing AMQP connection <0.371.0> (10.0.0.9:54226 -> 10.0.0.11:5672):
{writer,send_failed,{error,timeout}}

=INFO REPORT==== 6-Sep-2017::19:06:21 ===
accepting AMQP connection <0.1247.0> (10.0.0.9:36554 -> 10.0.0.11:5672)

=INFO REPORT==== 6-Sep-2017::19:06:21 ===
connection <0.1247.0> (10.0.0.9:36554 -> 10.0.0.11:5672): user 'guest' authenticated and granted access to vhost '/'

=ERROR REPORT==== 6-Sep-2017::19:06:26 ===
closing AMQP connection <0.430.0> (10.0.0.8:58214 -> 10.0.0.11:5672):
{writer,send_failed,{error,timeout}}

=INFO REPORT==== 6-Sep-2017::19:06:26 ===
accepting AMQP connection <0.1275.0> (10.0.0.8:37806 -> 10.0.0.11:5672)

=INFO REPORT==== 6-Sep-2017::19:06:26 ===
connection <0.1275.0> (10.0.0.8:37806 -> 10.0.0.11:5672): user 'guest' authenticated and granted access to vhost '/'

=ERROR REPORT==== 6-Sep-2017::19:07:07 ===
closing AMQP connection <0.1247.0> (10.0.0.9:36554 -> 10.0.0.11:5672):
{writer,send_failed,{error,timeout}}

=INFO REPORT==== 6-Sep-2017::19:07:07 ===
accepting AMQP connection <0.1299.0> (10.0.0.9:37600 -> 10.0.0.11:5672)

=INFO REPORT==== 6-Sep-2017::19:07:07 ===
connection <0.1299.0> (10.0.0.9:37600 -> 10.0.0.11:5672): user 'guest' authenticated and granted access to vhost '/'

=ERROR REPORT==== 6-Sep-2017::19:07:09 ===
closing AMQP connection <0.1275.0> (10.0.0.8:37806 -> 10.0.0.11:5672):
{writer,send_failed,{error,timeout}}

=INFO REPORT==== 6-Sep-2017::19:07:09 ===
accepting AMQP connection <0.1323.0> (10.0.0.8:38816 -> 10.0.0.11:5672)

=INFO REPORT==== 6-Sep-2017::19:07:09 ===
connection <0.1323.0> (10.0.0.8:38816 -> 10.0.0.11:5672): user 'guest' authenticated and granted access to vhost '/'

=ERROR REPORT==== 7-Sep-2017::04:33:30 ===
closing AMQP connection <0.1323.0> (10.0.0.8:38816 -> 10.0.0.11:5672):
{writer,send_failed,{error,timeout}}

=ERROR REPORT==== 7-Sep-2017::04:33:33 ===
closing AMQP connection <0.1299.0> (10.0.0.9:37600 -> 10.0.0.11:5672):
{writer,send_failed,{error,timeout}}

=INFO REPORT==== 7-Sep-2017::04:33:36 ===
accepting AMQP connection <0.1825.0> (10.0.0.8:35324 -> 10.0.0.11:5672)

=INFO REPORT==== 7-Sep-2017::04:33:36 ===
connection <0.1825.0> (10.0.0.8:35324 -> 10.0.0.11:5672): user 'guest' authenticated and granted access to vhost '/'
```

**Comment by np5** [comment]
Start by building a probe with the Zentral GUI, then export it as a gist. You will get a valid Zentral feed with the probe inside. Modify this JSON structure to suit you need, then host it somewhere, so that Zentral can download it. You can then import it as a feed.

**Comment by erdarun** [comment]
@np5 Thanks let me try it out.

We have 700+ machines enrolled till now but the events getting posted from all these machines takes more than 15 minutes to store in elastic search or reflect in kibana search. 

Is there any reason or need to do scaling of existing zentral workers? for now we have 2 instances running.

**Comment by np5** [comment]
Postgres: Try with [CONN_MAX_AGE](https://docs.djangoproject.com/en/1.11/ref/settings/#conn-max-age) in the Django DB settings.

Queue: Use the [rabbitmq_exporter](https://github.com/kbudde/rabbitmq_exporter) to export the rabbitmq metrics for prometheus. You will then see how fast you are producing events.

**Comment by erdarun** [comment]
Hi @np5 

CONN_MAX_AGE I tried with None value for max live period and small integer value as well but hasn't helped much. Even then we are facing Postgres DB filled with idle in transactions for  MachineSnapshot query. I have explicitly timed out "idle in transactions" but then idle transactions without any **query** or COMMIT statement gets piled up to max connections which is weird and database goes down.

Will give try on rabbitmq_exporter but as observed using "rabbitmqctl list_queues" "store_events_elasticsearch" queue grows in lakhs within 10 mins.

Is there any solution to support for large traffic from osquery say 1000 clients hitting zentral and each enroll/config/log API where I can see each api call needs database check for latest configs/hardware serial and machine snapshot. Is it cached using @cached_property?

Also Postgres MachineSnapshotCommit table has 33000 records where same machines have been enrolled multiple times with different versions. Is it required?

I have archived the dummy clients but now Im receiving duplicate key value violates unique constraint "inventory_machinesnapshotcommit_serial_number_f9fee8fa_uniq" for existing enrolled machines.

**Comment by np5** [comment]
How many total Zentral processes are you running ? Gunicorn processes + all the workers with the children processes.

**Comment by erdarun** [comment]
Zentral processes are 2 instances. We are not running gunicorn processes instead we are using runserver. Do we need to change that to gunicorn for performance improvements?

Frequency of osquery events is for every 10 minutes we have 65000+ events published to elastic search but the catch is elastic search store queue in parallel grows events waiting in lakhs at rabbitmq.

**Comment by np5** [comment]
Note that you can run an extra store worker without adding all the other workers. See the [runworkers](https://github.com/zentralopensource/zentral/blob/a03ab0b272a865a18e3e9228d8c6038ce9515914/server/base/management/commands/runworkers.py) command. With [docker-entrypoint.py](https://github.com/zentralopensource/zentral/blob/a03ab0b272a865a18e3e9228d8c6038ce9515914/docker-entrypoint.py), you can invoke it like that:

```bash
$ docker-compose run --rm workers runworkers --list-workers
```
to get a list of all the configured workers run by default (1 proc each).

To run an extra store worker, without adding all the extra workers (thus saving on postgres connections):

```bash
$ docker-compose run --rm workers runworkers 'store worker elasticsearch'
```

**Comment by np5** [comment]
About gunicorn:

[runserver](https://docs.djangoproject.com/en/1.11/ref/django-admin/#runserver) is not meant for production use:
> DO NOT USE THIS SERVER IN A PRODUCTION SETTING. It has not gone through security audits or performance tests. (And that’s how it’s gonna stay. We’re in the business of making Web frameworks, not Web servers, so improving this server to be able to handle a production environment is outside the scope of Django.)

I don't think it is the core of your problem here. You seem to be able to get most of the events sent by the clients. But, use a real web application server like [gunicorn](https://github.com/zentralopensource/zentral/blob/a03ab0b272a865a18e3e9228d8c6038ce9515914/docker-entrypoint.py#L61).

Another important thing:

Django [DEBUG](https://docs.djangoproject.com/en/1.11/ref/settings/#debug) settings

> Never deploy a site into production with DEBUG turned on.
>
> Did you catch that? NEVER deploy a site into production with DEBUG turned on.

Among the things that DEBUG turns on, the logging of all postgres queries. Another thing: a debug page on all 40x/500x errors. Not something you want to have in prod.

**Comment by erdarun** [comment]
Thanks @np5 for detailed description

gunicorn solves max connections issue. It's able to serve our load for now.

Yes, DEBUG was already false in production.

We are running 2 instances of runworkers in docker swarm. As you have suggested may be we will revisit for optimum no. of store workers/processors.

**Comment by np5** [comment]
So the only problem left is the duplicate key violation ? Could you try to find out the inventory source, if it concerns a lot of machines or only a few, and how often it happens ?

**Comment by erdarun** [comment]
Also we are getting frequent warnings like below,
```
base_extras WARNING App zentral.contrib.jamf w/o main menu config
base_extras WARNING App zentral.contrib.simplemdm w/o main menu config
base_extras WARNING App zentral.contrib.munki w/o main menu config
base_extras WARNING App zentral.contrib.nagios w/o main menu config
base_extras WARNING App zentral.contrib.osquery w/o main menu config
base_extras WARNING App zentral.contrib.santa w/o main menu config
base_extras WARNING App zentral.contrib.inventory w/o setup menu config
base_extras WARNING App zentral.core.probes w/o setup menu config
```

**Comment by np5** [comment]
Maybe it should not be logged at the `WARNING` level, but at the `INFO` level.

The template tag used to build the main menu [looks for](https://github.com/zentralopensource/zentral/blob/a03ab0b272a865a18e3e9228d8c6038ce9515914/server/base/templatetags/base_extras.py#L29) a `main_menu_config` in the `urls.py` files of the active Zentral modules. Some of them have one, and a menu is displayed (like [monolith](https://github.com/zentralopensource/zentral/blob/a03ab0b272a865a18e3e9228d8c6038ce9515914/server/base/templatetags/base_extras.py#L29)). Some of them don't.

This issue is epic…

**Comment by np5** [comment]
Someone is knocking at the door…

**Comment by erdarun** [comment]
@np5 Do you mean intrusion?

**Comment by np5** [comment]
Well, this is obviously a web crawler trying to find out what is running on you Zentral server.
