### ISSUE TITLE
Issues when including Santa installer with Santa Enrollment 

### ISSUE THREAD

**Issue by avantgardefuselage** [zentralopensource/zentral#49]
Including the santa installer with the santa enrollment ends up with errors: 

```
[~] santactl sync
Missing Machine Owner.
HTTP Response: -1002 unsupported URL
Preflight failed, aborting run
```

The file `/var/db/santa/config.plist` looks similar to:

```
~] sudo defaults read /var/db/santa/config.plist
Password:
{
    ClientMode = 1;
    FullSyncLastSuccess = "2017-09-06 12:45:29 +0000";
    MachineID = "%MACHINE_ID%";
    RuleSyncLastSuccess = "2017-09-06 12:45:29 +0000";
    ServerAuthRootsFile = "/usr/local/zentral/tls_server_certs.crt";
    SyncBaseURL = "https://zentral.website.com/santa/";
}
```
MachineID does not get filled in correctly.

Running the Santa enrollment _without_ the Santa installer bundled works fine. MachineID gets filled in just fine.

**Comment by np5** [comment]
We have observed this issue too.

I don't think there is a bug in the [postinstall script](https://github.com/zentralopensource/zentral/blob/a03ab0b272a865a18e3e9228d8c6038ce9515914/zentral/contrib/santa/osx_package/build.tmpl/scripts/postinstall#L5).

Maybe it could help to stop santa before editing the configuration.

**Comment by np5** [comment]
Does 8fb5106 fix the issue ? We have tried it and it seems to work better.

**Comment by np5** [comment]
After testing at the workshop in Göteborg with 20 different machines, I think the problem with `%MACHINE_ID%` is solved.

But a new issue was found. The file `/var/db/santa/config.plist`was sometimes created with `0600` permissions, blocking the `santactl sync` command that needs to read this file, and needs `0644`.

Here is a terminal session while the installer was running. Before the final scripts are run, the file is copied from the installer with the correct rights (first `ls` command). After the installer has run, the other files are present, and the config.plist has `0600` permissions (second `ls`command). This prevents `santactl` from running. Reverting the permissions to `0644` allows it to run:

![santa install issue - 10 12 4](https://user-images.githubusercontent.com/319001/31434577-ff572038-ae7c-11e7-9949-4172144b4771.png)

**Comment by np5** [comment]
It seems that the [defaults write call](https://github.com/zentralopensource/zentral/blob/cf632f944102e6a62a65b67f809e6ac0698fda8a/zentral/contrib/santa/osx_package/build.tmpl/scripts/postinstall#L9) to set `MachineID` changes the permissions on `config.plist` for some systems.

**Comment by np5** [comment]
The problem is not solved. Sorry.

**Comment by np5** [comment]
New config method in a83b5a1. Everything is done in the postinstall script. We wait 1 second after we stop stantad.

**Comment by np5** [comment]
Since 0cb915e3eb612f2e903eb2a11591d84c9313e8c7, enrollment packages are not used anymore for Santa.
