### ISSUE TITLE
Home page enhancements

### ISSUE THREAD

**Issue by jbaker10** [zentralopensource/zentral#5]
Hi there!

This is not so much an issue as much of an inquiry or enhancement request. I have been using Zentral just briefly, but very much enjoying it thus far. One thing I noticed right off the bat was the blank "Home" page if you will, that just says "Zentral".

I was wondering if there had been consideration to add anything to that, for instance graphs? I think it would be really nice to add a quick overview of a few things right when you get there (great for management folks kind of stuff), such as:
- How many computers enrolled in osquery/santa
- How many machines that meet an alert from osquery (or santa, etc.)
- How many business units, and how many machines in each business unit

Just something at a broad scale to 1) kind of pretty up the first thing you see, and 2) give some good easy insight into your Zentral system. I am not very django-savvy, but will definitely look at whipping something together should others consider this useful.

Thanks again for your work on this product, it's great!
-Jeremy

**Comment by headmin** [comment]
thanks we consider changes in that area, stay tuned

**Comment by np5** [comment]
For each enabled module we display two graphs now, one for the number of events, one for the number of machines involved.

**Comment by jbaker10** [comment]
👍 👍 👍
