### ISSUE TITLE
Logging of Zentral login events

### ISSUE THREAD

**Issue by nishitm** [zentralopensource/zentral#51]
I wanted to log each log-in tries(successful/unsuccessful) on zentral. How and where I should configure this settings in zentral?

Thanking you for help in advance.

**Comment by headmin** [comment]
this is already build in event type. you can create a probe for "event" type then filter for :

zentral_failed_login
zentral_login
zentral_logout

trigger actions same way as with other probes (i.e. slack channel to post login, failed login events)
