### ISSUE TITLE
Password Expiration Feature in Zentral

### ISSUE THREAD

**Issue by nishitm** [zentralopensource/zentral#52]
Hi, 
Is there a feature like login password expiration on zentral? So to do this I think django middleware needs to be added. 

Please help if you have any clue..
Thanking you in advance

**Comment by headmin** [comment]
Hi, we think the implemented SAML option is sufficient for such need. much better control and include SSO, 2FA, etc.

**Comment by nishitm** [comment]
Thank you @headmin . One more question, If I want to implement force password expiry then how should I approach?

**Comment by headmin** [comment]
watch the upcoming commits. there will be some changes incl. MAX_PASSWORD_AGE_DAYS (for non SAML)

**Comment by np5** [comment]
See 50b04928a

You could add this to the `django` section of your `base.json`:

```
"AUTH_PASSWORD_VALIDATORS": [
  {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
   "OPTIONS": {"min_length": 8}},
  {"NAME": "accounts.password_validation.PasswordNotAlreadyUsedValidator",
   "OPTIONS": {"min_unique_passwords": 10}}
],
"MAX_PASSWORD_AGE_DAYS": 60
```

This will check that the passwords are at least 8 characters long, that they are different than the last 10 passwords used (per user), and that they have been changed in the last 60 days (after that, the user is redirected to the password change form.)

Note that they are some [other validators](https://docs.djangoproject.com/en/1.11/topics/auth/passwords/#module-django.contrib.auth.password_validation) built in Django. You can add them to `AUTH_PASSWORD_VALIDATORS`.

**Comment by nishitm** [comment]
@np5 and @headmin  Thank you for this great help !!!
