### ISSUE TITLE
Zentral Syslogging

### ISSUE THREAD

**Issue by Kshitij29** [zentralopensource/zentral#55]
I want to log all the zentral login and logout events to a syslog server. I see login and logout events create logs but when I try to syslog, all the events( login, logout as well as heartbeats) are logged through syslog. How can I filter between heartbeats and login/logout events through syslog?

**Comment by headmin** [comment]
Right now there is no filter facility for syslog out. Syslog is used as a event-store (as ES). 
see commit here: https://github.com/zentralopensource/zentral/commit/195ce29d3bd8720b3745ee0c3196a3ab0736f6e9#diff-6d67768dab2607b0322de6bfa3b792f8

Depending on your organization size and requirements: 
A possible solution for a monitored audit trail for login, failed login and failed 2FA usage ->  create an events probe, use Metadata filter for all login/logout/failed-login event types, and trigger action to team-chat (slack) 
<img width="951" alt="screen shot 2017-10-24 at 12 03 18" src="https://user-images.githubusercontent.com/46750/31937029-96e96588-b8b3-11e7-985e-ef3ccd95cae0.png">

**Comment by Kshitij29** [comment]
Thank you @headmin . But what action type is it? When I try to add the action for metadata filter I see only "debug" as the action type.

**Comment by headmin** [comment]
@Kshitij29 you can define various actions in `base.json`config file, have a look into the tutorials section here: https://github.com/zentralopensource/zentral/wiki/tutorial-ref#episode-05---setupactions-enable-zentral-notifications-to-slack-use-slack-webhooks

**Comment by Kshitij29** [comment]
Sure. Thanks @headmin
