### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by adrianog** [zentralopensource/zentral#56]
Hi and thanks for the resource.

Is there a docker image for Zentral?

**Comment by headmin** [comment]
We use docker-compose, look here:

https://github.com/zentralopensource/zentral/wiki/deployment-docker

**Comment by adrianog** [comment]
Thanks.

I see the instructions are centered on mac, but I'm planning on having this on a container on a remote server instead.

Any word of advice/alert if I go down that route?

**Comment by np5** [comment]
If you want to evaluate Zentral, the easiest way is to spin up a test instance on the Amazon or Google cloud services. We have uploaded images containing a full Zentral setup on those platforms. Everything works out of the box.
