### ISSUE TITLE
Client Enrollment script for Linux/CentOS 

### ISSUE THREAD

**Issue by mayamary** [zentralopensource/zentral#62]
Hi
Do we have osquery enrollment script for CentOS/linux.

**Comment by mayamary** [comment]
Thanks, this is good. 
But I actually need to configure zentral server in client osquery in Linux. I can't able to see any codes for Linux OS.
I need something like this https://github.com/zentralopensource/docs/blob/master/zentral-client-enroll.md?utf8=%E2%9C%93 for Linux.
Please help me.

**Comment by np5** [comment]
But the form is exactly what you need. You can find it under the "Setup" tab, in "Osquery" > "Enrollment". Once you have filled it, click on the "Linux apt/yum setup script", and you will get a configured bash script for your Zentral instance, that you can directly run as root on your clients to enroll them. This will download and install osquery (if you choose an osquery release in the form), configure osquery, install your zentral server certs, and start osqueryd.

**Comment by mayamary** [comment]
@np5  Thanks,this is working.After getting our client details  under Inventory Tab ,I have create new osquery probe for that machine ,can't able to get events  from osquery probe.
I need the step to "how to create new osquery  Probe and also events trigger .

**Comment by mayamary** [comment]
issue solved
