### ISSUE TITLE
Enroll packages is corrupt after AWS upgrade 

### ISSUE THREAD

**Issue by AndersTao** [zentralopensource/zentral#65]
I just installed a new instant af Zentral AWS following the [Wiki](https://github.com/zentralopensource/zentral/wiki/deployment-aws)

After upgrading to the latest with `sudo /home/zentral/app/utils/deploy.py` all macOS packages has corrupt postinstall scripts (testet muni, ossuary and santa) and is unable to install

![screen shot 2018-07-04 at 09 48 47](https://user-images.githubusercontent.com/1774117/42269118-94ec3012-7f7d-11e8-87e7-556ce8c5250c.png)

**Comment by np5** [comment]
We forgot to update the Zentral all in one image, after we [fixed the packaging](https://github.com/zentralopensource/zentral/commit/724a69df71da6e9b3a19900ddf08cf17f361b5be). Sorry for that. We will publish new images today.

In the meantime, you can install `bsdcpio`:
```
sudo apt update && sudo apt install bsdcpio
```
This should fix your issue.

**Comment by headmin** [comment]
I can confirm @np5 fix here on a AWS based Zentral all in one instance

**Comment by AndersTao** [comment]
Thanks @np5 this did solve the problem, now the packages can install

The OSquery package is installing, and reporting back, but the Santa package i running into a problem.

Maybe the *%TLS_HOSTNAME%* variable should be translated before package generation? 
This is the post install script from my package created after the `bsdcpio` fix
```
#!/bin/bash

# postinstall

# unload com.google.santad.plist
/bin/launchctl unload "/Library/LaunchDaemons/com.google.santad.plist"

# sleep, because …
sleep 1

# do enrollment
/usr/local/zentral/santa/enroll.py

# copy old style configuration
cp "/usr/local/zentral/santa/config.plist" "/var/db/santa/config.plist"
# fix old style configuration permissions
chmod 0644 /var/db/santa/config.plist

# load com.google.santad.plist
/bin/launchctl load -w "/Library/LaunchDaemons/com.google.santad.plist"

# write zentral base url
defaults write /Library/Preferences/io.zentral.plist base_url "https://%TLS_HOSTNAME%"

# force santa sync (=> preflight => machine_id => serial number)
/usr/local/bin/santactl sync

exit 0
```

**Comment by np5** [comment]
Fixed in 08818d6

**Comment by headmin** [comment]
validated over here.

**Comment by AndersTao** [comment]
I created a new node, and was able to update to the latest version

But no events is reporting back!
I can push out santa rules, but no event is returnet to zentral, to trigger actions

**Comment by AndersTao** [comment]
Just to make sure I didn't do anything stupid, I created a new node, and did nothing else then running setup.py, and then updating with `deploy.py`
Running the upgrade ends with `Found 29937 MAC assignments. Use --update to update`

[Migration issues](https://github.com/zentralopensource/zentral/wiki/deployment-aws#migration-issues) inform to run `sudo ZENTRAL_CONF_DIR=/home/zentral/conf /home/zentral/app/venv/bin/python /home/zentral/app/repository/server/manage.py import_mac_assignments` but this also return `Found 29937 MAC assignments. Use --update to update`

Adding `--update` to the end start the update
```
$ sudo ZENTRAL_CONF_DIR=/home/zentral/conf /home/zentral/app/venv/bin/python /home/zentral/app/repository/server/manage.py import_mac_assignments --update
Import https://standards.ieee.org/develop/regauth/oui/oui.csv
100%|█████████████████████████████| 25091/25091 [01:07<00:00, 372.83it/s]
Import https://standards.ieee.org/develop/regauth/oui28/mam.csv
100%|█████████████████████████████| 2115/2115 [00:05<00:00, 374.79it/s]
Import https://standards.ieee.org/develop/regauth/oui36/oui36.csv
100%|█████████████████████████████| 2737/2737 [00:07<00:00, 372.17it/s]
```

I then re-run `deploy.py`,  but still see the the same message
```
...
Running migrations:
  No migrations to apply.
Found 29937 MAC assignments. Use --update to update.
```

**Comment by np5** [comment]
There is a call to `import_mac_assignments` without the `--update` flag in `deploy.py`, to make sure that some mac assignments are present in the DB. That's why you see this output. Everything is fine, there are already ~30000 assignments in the DB. If you really want to make sure that they are up to date, you should run `import_mac_assignments` with the `--update` flag.

The MAC assignments are absolutely not critical. There are just there to be able to display a manufacturer name next to the MAC address. Running `import_mac_assignments` doesn't fix the migrations, and should not be necessary when the `zentral-all-in-one` images are recent.

**Comment by AndersTao** [comment]
Thanks for verifying @np5

Just added one client, with a santa enrollment pkg, the new client show up in Zentral, but with no events or heartbeat.

running `santactl sync` after adding a new probe looks right on the client
```
$ santactl sync
Missing Machine Owner.
Uploaded 1 events
Added 1 rules
Sync completed successfully
```
Events for the client in Zentral is still blank
<img width="1175" alt="screenshot 2018-07-05 at 11 51 11" src="https://user-images.githubusercontent.com/1774117/42316309-bc6e0ff8-8049-11e8-80d6-5bef8629d385.png">
<img width="931" alt="screenshot 2018-07-05 at 11 51 36" src="https://user-images.githubusercontent.com/1774117/42316340-c8992e70-8049-11e8-9539-75ae6232ddf2.png">

**Comment by np5** [comment]
It seems that elasticsearch is not working or the zentral workers are not up, which is weird.

Can you check in "Extra links > Prometheus", then "Status > Targets", to see if all the workers are up (should all be green) ?

What happens when you go to "Extra links > Kibana" and configure kibana to access the "zentral-events" index ?

**Comment by AndersTao** [comment]
**A lot of red in Prometheus**
<img width="2118" alt="screenshot 2018-07-05 at 12 51 28" src="https://user-images.githubusercontent.com/1774117/42319457-52bffcf2-8052-11e8-963b-7883c2984c0b.png">

**Looks okay ?**
<img width="1467" alt="screenshot 2018-07-05 at 12 52 41" src="https://user-images.githubusercontent.com/1774117/42319458-52d9c8da-8052-11e8-810a-80db8e0ec58a.png">

**Comment by np5** [comment]
OK, so, somehow, the workers are not up, which is unusual. I've just tried all the steps again, and I was able to get the events. All the components were up.

Could you try to restart the workers ?

```
sudo systemctl restart zentral_workers.service
```

**Comment by AndersTao** [comment]
Restart of the service did it! Everything is green and up

Thanks for the followup @np5

**Comment by np5** [comment]
I have just pushed 3b683fd. This fixes a race detection issue, when the workers start, and the index is missing. This is probably what happened.
