### ISSUE TITLE
403 forbidden 

### ISSUE THREAD

**Issue by rnddave** [zentralopensource/zentral#68]
Hi,

Probably not an issue, but something I'm struggling with. I have used Docker Compose to bring this up on a Mac, the Mac is already running 2 other web based services so I have changed the config to bring up ngnix using port 8083 rather than 443, this is essentially my only diversion from a standard build. 

I bring up the service without issue, but when I go to the admin password reset page I see Zentral, then as I press the button to reset my password I receive the a 403 Forbidden error. 

**Forbidden (403)
CSRF verification failed. Request aborted.**

> Reason given for failure:
> 
> Referer checking failed - https://zentral:8083/accounts/login/?next=/ does not match any trusted origins.

I've looked at the web logs; 

`web_1       | 2018-08-15 17:41:00,904 PID35 basehttp INFO "GET /inventory/prometheus_metrics/ HTTP/1.1" 200 735
web_1       | 2018-08-15 17:41:05,034 PID35 csrf WARNING Forbidden (Referer checking failed - https://zentral:8083/reset/MQ/4yr-3982fdf7c83d300def27/ does not match any trusted origins.): /reset/MQ/4yr-3982fdf7c83d300def27/
web_1       | 2018-08-15 17:41:05,051 PID35 basehttp WARNING "POST /reset/MQ/4yr-3982fdf7c83d300def27/ HTTP/1.0" 403 2587`

Any pointers on where I can focus my troubleshooting with regard to this?

**Comment by np5** [comment]
This has to do with the way Django is getting the host information behind nginx. It is not really working as is if the exposed nginx port is changed in docker-compose.yml.

To make it work, you have to make 2 changes

1) in the nginx conf, replace [this line](https://github.com/zentralopensource/zentral/blob/a000fb314ba514488df49dcc3d2106001948ea3b/conf/start/docker/nginx/conf.d/zentral.conf#L62) with:

`proxy_set_header   X-Forwarded-Host $host:8083;`

2) in the [django settings](https://github.com/zentralopensource/zentral/blob/master/server/server/settings.py), add this line:

`USE_X_FORWARDED_HOST = True`

this way, the `request.get_host()` Django method will return `zentral:8083`, and the CSRF referrer check will pass.

**Comment by np5** [comment]
Do not forget to edit the [base.json](https://github.com/zentralopensource/zentral/blob/a000fb314ba514488df49dcc3d2106001948ea3b/conf/start/zentral/base.json#L3) file and add the port to the tls_hostname.

**Comment by rnddave** [comment]
Thanks so much @np5 - this has fixed things for me, really appreciate your help.
