### ISSUE TITLE
'FATAL:  sorry, too many clients already' trying to load the Zentral homepage

### ISSUE THREAD

**Issue by jkish2** [zentralopensource/zentral#69]
**What deploymment method are you using ?**
Docker

**What operating system are you using?**
CentOS

**What did you do?**
Attempted to load the Zentral home page by navigating to the URL. Restarted the CentOS server, then restarted the containers using `docker-compose up -d` to no avail.

**What did you expect to see?**
Expected to see the Zentral login screen.
<img width="677" alt="screen shot 2018-10-25 at 9 51 21 pm" src="https://user-images.githubusercontent.com/4182189/47576090-a45c8b80-d911-11e8-842f-c90286bb30bc.png">

**Comment by jkish2** [comment]
I've increased the `max_connections` in `/var/lib/postgresql/data/postgresql.conf` from 100 to 1500. While I'm not seeing the error above anymore, I am getting a 404 page from `nginx`. Any thoughts?

**Comment by np5** [comment]
We run a production installation of Zentral with other 500 clients, and the current connection count to postgresql is 11 (```select count(*) from pg_stat_activity;```). It is really hard for me to help you without more information about your setup.

* Did you change anything in the ```base.json``` configuration ?
* Are you running Centos locally on your laptop, or on a server ?
* Did you change the FQDN, did you setup the certificates accordingly and updated the Django and nginx configuration ?
* Do you run nginx as a container ? If so, did you restart the nginx container after recreating/restarting the web container ?

And, I would strongly suggest to turn off the Django debugging if you are running Zentral on a server directly exposed to the internet.

**Comment by jkish2** [comment]
_Did you change anything in the base.json configuration ?_

The only changes that were made to `base.json` were customizing the `tls_hostname` and `tls_server_certs` entries.

_Are you running Centos locally on your laptop, or on a server ?_

CentOS is running in a virtual server in our datacenter.

_Did you change the FQDN, did you setup the certificates accordingly and updated the Django and nginx configuration?_

These were updated as per https://youtu.be/gmF0jaDbZ7o?t=196.

_Do you run nginx as a container? If so, did you restart the nginx container after recreating/restarting the web container?_

nginx is running as a container. This was setup automatically when we used `docker-compose up -d` to setup Zentral once the certificate and FQDN were customized.

Running `select count(*) from pg_stat_activity;` currently shows that the current connection count is only 7. I should note that we have Kibana running in a container as well and we've opened up port `9200` on `zentral_elastic_1` so Grafana can access this data as well.

**Comment by jkish2** [comment]
![screen shot 2018-10-29 at 1 04 39 pm](https://user-images.githubusercontent.com/4182189/47667044-65ca0980-db7b-11e8-847a-d3c1358b1e37.png)

**Comment by np5** [comment]
Did you try to restart only the nginx container ?

Could you post the nginx logs and the web logs ?

```docker-compose logs --tail=200 nginx```

```docker-compose logs --tail=200 web```

**Comment by jkish2** [comment]
Sorry for the delayed response. It appears that the issue was storage:

`Filesystem                  Size  Used Avail Use% Mounted on
/dev/mapper/vg_root-lv_var  124G  118G  6.8G  95% /var`

Since we weren't using any of the data for production yet, I was able to just delete everything and set it up from scratch successfully.

Thanks for your help!
