### ISSUE TITLE
NoReverseMatch at /inventory/ when looking for Linux in inventory

### ISSUE THREAD

**Issue by jkish2** [zentralopensource/zentral#70]
We recently enrolled a Linux VM with Zentral and confirmed that it appears in the count of total machines in the inventory. However, when we try to search for this machine using the Platform dropdown, we receive the following error.

![screen shot 2018-11-08 at 4 15 39 pm](https://user-images.githubusercontent.com/4182189/48227865-9545f680-e371-11e8-9f86-e54fa6501e0c.png)

We've also been able to locate and view the information successfully using Kibana, just not using the Zentral UI.

Any ideas?

**Comment by np5** [comment]
Hi,

Yes, it is the first time we see a serial number with space characters, and the [URL routing](https://github.com/zentralopensource/zentral/blob/062c635226e313764e24deedd86f92c79cf42cf9/zentral/contrib/inventory/urls.py#L28) cannot find a match.

I will get back to you as soon as I have a solution.

**Comment by np5** [comment]
I have just pushed 3 commits that should fix the issue with the unusual serial numbers. The "normal" ones are used as before in the URLs, the ones with some restricted characters are base64 encoded.

**Comment by jkish2** [comment]
That did the trick. Thanks for your help and the quick turn around on this one!
