### ISSUE TITLE
Add identifier patterns for signing ID rules to API

### ISSUE THREAD

**Issue by wmssj** [zentralopensource/zentral#709]
Identifiers in the formats "platform:com.apple.Application" and "TEAMID:com.vendor.Application" are currently rejected by the API with error "This value does not match the required pattern." when attempting to create a ruleset containing a Signing ID rule.

**Comment by np5** [comment]
Which API endpoint are you using ?

**Comment by np5** [comment]
Oh, I see, you are using the ruleset endpoint. I will fix this issue.

**Comment by np5** [comment]
It should work now. Thanks for reporting the issue.
