### ISSUE TITLE
[Question]Zentral remove/disable santa probes not syncing

### ISSUE THREAD

**Issue by kilroykissenger** [zentralopensource/zentral#71]
I can create probes and sync them to my clients but when I disable the probes (and resync) the machines still get Santa blocks when running the binaries or the files. Issue occurs with multiple versions of Santa (0.9.19,0.9.20,0.9.30). Currently running 0.9.30 
Syncing says completed successfully (even with a no computer owner error).

**Comment by np5** [comment]
This is maybe not intuitive, but you need to change the policy of the rule if you want to revert its effect. Choose "Remove" for example, and let the probe active for a while. We could have done it automatically, for blacklist or whitelist rules of disabled santa probes, but it seemed like to much magic (and not really great if a new machine gets the remove rule 1 year after the probe was disabled).
