### ISSUE TITLE
Allow adding arbitrary options to Osquery configuration

### ISSUE THREAD

**Issue by vector-sec** [zentralopensource/zentral#74]
Today in Zentral I can only configure the options config_refresh, distributed_interval, and a few others from /osquery/configurations/<id>/

When trying to use extensions like https://github.com/polylogyx/osq-ext-bin this is a problem because the extension has an extensive list of custom configuration options that it understands and may require to be present.

Since the config is valid JSON, would adding a field to the configuration in Zentral that accepts (and validates) a JSON string of additional options be possible?

**Comment by np5** [comment]
Sorry for the late reply.

It seems that for this extension, this would be the only way to do it. Do you know of any other extension that uses the same configuration mechanism ?

**Comment by np5** [comment]
fixed in b24befcfe1f092944a4c7f7d4c4c4d122433e70f
