### ISSUE TITLE
Not able to find the all-in-one gzip 

### ISSUE THREAD

**Issue by tonynotears** [zentralopensource/zentral#77]
gcloud compute images create zentral-all-in-one --source-uri gs://zentralopensource/zentral-all-in-one.tar.gz

ERROR: (gcloud.compute.images.create) Could not fetch resource:
 - The resource 'https://www.googleapis.com/storage/v1/b/zentralopensource/o/zentral-all-in-one.tar.gz' of type 'Google Cloud Storage object' was not found.

Can you please help resolving this issue ?Thanks

**Comment by headmin** [comment]
please have a look into this blogpost which explain simple steps to fix this https://medium.com/@Torbjorn_59818/working-around-ec68e565e284
