### ISSUE TITLE
Accept unusual Google identifiers for Signing ID Santa rules via ruleset API and rules/create in web interface

### ISSUE THREAD

**Issue by wmssj** [zentralopensource/zentral#788]
Google uses underscores in the signing IDs for some of their binaries for Chrome and Drive; attempts to add Santa rules for these signing IDs via the ruleset API and Zentral's web interface are both rejected. For example, a rule with identifier EQHXZ8M8AV:chrome_crashpad_handler is rejected by the ruleset API with the error "This value does not match the required pattern." and by the web interface with the error "Invalid Signing ID target identifier". Other examples (all with the same Team Identifier) are: app_mode_loader, crashpad_handler, load_dfsfuse, mount_dfsfuse, mount_helper, and switchblade_host

Can the input parser for Santa signing ID rules be tweaked to accept these values?

**Comment by np5** [comment]
Thank you for reporting this issue!
