### ISSUE TITLE
setup.py results in "Waiting for kibana..." indefinitely

### ISSUE THREAD

**Issue by dherder** [zentralopensource/zentral#84]
**Summary**
When running setup.py, with fqdn, username, email, the following output is generated <truncated>:
Generate new dhparam ...
Generating DSA parameters, 4096 bit long prime
......+.......................+....+....+++++++++++++++++++++++++++++++++++++++++++++++.+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*
New dhparam generated
Waiting for kibana...................................................................................................................................................................

Thus, no superuser seems to be generated, and no password reset link is generated.

**Troubleshooting Steps Taken**
-- executed sudo /home/zentral/app/utils/deploy.py to update to latest code.
-- ensured fqdn is resolvable, ports opened
-- attempted to look at /var/log/kibana.log, which was not present

**Environment**
gcloud deployment, deploy.py run on update 06/25/2019

**Observed Result**
-- kibana never starts, thus password reset link is never generated
-- fqdn of zentral instance is resolvable in browser.

**Expected Result**
-- kibana starts and password reset link is generated and presented to user.

**Comment by np5** [comment]
Quick thing: no need to run `deploy.py` before the `setup.py` run.

You could run `sudo systemctl status kibana` or `journalctl -u kibana.service`, to get more information. Kibana is definitely installed in the image, maybe it is not starting because the system is running out of RAM => Instance type / size ?

**Comment by dherder** [comment]
I had used the default instance size, 1vCPU. I modified to 2vCPU (did not modify RAM) and kibana started OK.
