### ISSUE TITLE
Docker build fails libssl1.0-ssl 

### ISSUE THREAD

**Issue by Bretterteig** [zentralopensource/zentral#85]
Trying to set up the docker build. 
I get the error:
E: Package 'libssl1.0-dev' has no installation candidate

I tried libssl-dev but it failed with:
configure: error: Cannot build without libcrypto (OpenSSL)

**Comment by np5** [comment]
The base distribution for the python docker image has indeed changed to debian buster. I will look into it.

**Comment by np5** [comment]
Fixed with ee8939aa. A more elegant solution would be to fix or fork [xar](https://github.com/mackyle/xar/blob/66d451dab1ef859dd0c83995f2379335d35e53c9/xar/configure.ac#L332).
