### ISSUE TITLE
No any response in resetting password session

### ISSUE THREAD

**Issue by tintranvan** [zentralopensource/zentral#88]
Hi,

I've installed Zentral by Docker-Compose with 
Docker - 18.09
Docker - Compose - 1.24.0

docker containers information:

       Name                     Command               State                    Ports
zentral_celery_1     /zentral/docker-entrypoint ...   Up
zentral_db_1         docker-entrypoint.sh postgres    Up      5432/tcp
zentral_elastic_1    /usr/local/bin/docker-entr ...   Up      9200/tcp, 9300/tcp
zentral_nginx_1      nginx -g daemon off;             Up      0.0.0.0:443->443/tcp, 80/tcp
zentral_promsrv_1    /bin/prometheus --config.f ...   Up      9090/tcp
zentral_rabbitmq_1   docker-entrypoint.sh rabbi ...   Up      25672/tcp, 4369/tcp, 5671/tcp, 5672/tcp
zentral_web_1        /zentral/docker-entrypoint ...   Up
zentral_workers_1    /zentral/docker-entrypoint ...   Up

------------------------------------------------------------------------------------

When i try to reset password by URL: https://zentral.axonactive.vn.local/reset/MQ/set-password/, 
the page's loaded so long, seem there is no any response from server.
I've try many times but this problem still happend.

Could you please help me to resolve this case.

Thansks and Best Regards,

**Comment by np5** [comment]
Does the zentral.axonactive.vn.local domain resolve correctly ?

Can you tail the nginx logs (`docker-compose logs -f --tail=100 nginx`), make simple requests (`curl -kv https://127.0.0.1`) and see the log lines with the 302 redirects ?

**Comment by np5** [comment]
Dead issue. This has been working fine in dev and prod environments for ages now.
