### ISSUE TITLE
Postgres database cleanup.

### ISSUE THREAD

**Issue by SkylarTheDialer** [zentralopensource/zentral#91]
The database for my Zentral instance is nearly 20GB, most of it being the inventory_machinesnapshotcommit table (4 million+ rows). I'm experiencing very slow performance in the web UI and would like to rule out the database as the culprit. 

Is there a way to recreate the postgres database, and retain the already existing business units?

**Comment by np5** [comment]
There is a `cleanup_inventory_history` django management command that should be run regularly to prune the inventory history. I could tell you how to run it, but i need to know what is your setup before.

**Comment by np5** [comment]
No answer…
