### ISSUE TITLE
Filebeat enrollment .pkg cannot be installed on macOS 10.15

### ISSUE THREAD

**Issue by voxxit** [zentralopensource/zentral#92]
When I try to install the package, I get the following message:

<img width="734" alt="Screenshot 2020-01-05 09 41 43" src="https://user-images.githubusercontent.com/12201/71783705-97b8d600-2f9f-11ea-954c-6ad7a815a7b9.png">

The issue stems from the `postinstall` script, which when I remove and run separate from the installer, emits this error:

```
asn1: structure error: tags don't match (16 vs {class:0 tag:28 length:104 isCompound:true}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} certificate @2
Traceback (most recent call last):
  File "/Users/xxx/Desktop/postinstall", line 161, in <module>
    client_cert, client_key = get_certificate(serial_number, **enrollment_session_data["scep"])
  File "/Users/xxx/Desktop/postinstall", line 121, in get_certificate
    "-certificate", "client.crt"
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/zentral/bin/scepclient', '-server-url', u'https://xxx-clicertauth.xxx.com/scep', '-private-key', 'client.key', '-certificate', 'client.crt']' returned non-zero exit status 1
```

Could this be an OS-related issue? Thank you in advance for the assistance.

**Comment by np5** [comment]
The FQDNs that you used during the zentral setup have to resolve correctly, and I am pretty sure you do not own the xxx dot com domain ;-)

**Comment by voxxit** [comment]
@np5 I am aware of that... 😄 I removed them on purpose for security purposes.

**Comment by np5** [comment]
Can you tell me more about your setup ? So you have the micromdm scepserver running on your server ?

**Comment by voxxit** [comment]
@np5 I actually followed the process outlined in the wiki to launch the Zentral AWS AMI.

**Comment by np5** [comment]
Did you use the latest images or did you upgrade from an older image ?

Do you have micromdm/scepserver running on your instance ?
`systemctl status scepserver.service`

Can you see errors in the scepserver logs?
`journalctl -u scepserver.service`

Can you see relevant errors in the zentral web app logs?
`journalctl -u zentral_web_app.service`

Can you see "filebeat enrollment" events (event probe on type "filebeat enrollment") ?

**Comment by np5** [comment]
No answer…
