### ISSUE TITLE
Zentral cannot create Webhooks

### ISSUE THREAD

**Issue by zacharysfisher** [zentralopensource/zentral#95]
Hello I can't seem to have Zentral create webhooks.  I get this error:

Could not setup webhooks on https://intersection.jamfcloud.com:443.

I have verified API credentials.  Where can I get more indepth logs?

**Comment by np5** [comment]
Hello,

What kind of setup are you running ?

**Comment by zacharysfisher** [comment]
It is running in AWS on an ubuntu instance, all in one image from
Marketplace.

**Comment by np5** [comment]
You can run ```journalctl -f -u zentral_web_app.service``` to stream the web app logs in a terminal. After that, try to setup the Jamf webhooks again. You should be able to see a slightly more detailed error.

**Comment by zacharysfisher** [comment]
See below.

`2020-03-16 13:08:50,269 PID1752 log ERROR Internal Server Error: /jamf/post_event/r5G1KbsV1OIeAkJlNZO3OJQi6ZoK4dN0EwEUu7n0vaeg00nwxbMku1jpTBNBuXDveWe/
Mar 16 09:08:50 zentral-server.COMPANY.com gunicorn[1291]: Traceback (most recent call last):
Mar 16 09:08:50 zentral-server.COMPANY.com gunicorn[1291]:   File "/home/zentral/app/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
Mar 16 09:08:50 zentral-server.COMPANY.com gunicorn[1291]:     response = get_response(request)
Mar 16 09:08:50 zentral-server.COMPANY.com gunicorn[1291]:   File "/home/zentral/app/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
Mar 16 09:08:50 zentral-server.COMPANY.com gunicorn[1291]:     response = self.process_exception_by_middleware(e, request)
Mar 16 09:08:50 zentral-server.COMPANY.com gunicorn[1291]:   File "/home/zentral/app/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
Mar 16 09:08:50 zentral-server.COMPANY.com gunicorn[1291]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Mar 16 09:08:50 zentral-server.COMPANY.com gunicorn[1291]:   File "/usr/lib/python3.5/contextlib.py", line 30, in inner
Mar 16 09:08:50 zentral-server.COMPANY.com gunicorn[1291]:     return func(*args, **kwds)
Mar 16 09:08:50 zentral-server.COMPANY.com gunicorn[1291]:   File "/home/zentral/app/venv/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
Mar 16 09:08:50 zentral-server.COMPANY.com gunicorn[1291]:     return view_func(*args, **kwargs)
Mar 16 09:08:50 zentral-server.COMPANY.com gunicorn[1291]:   File "/home/zentral/app/venv/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
Mar 16 09:08:50 zentral-server.COMPANY.com gunicorn[1291]:     return self.dispatch(request, *args, **kwargs)
Mar 16 09:08:50 zentral-server.COMPANY.com gunicorn[1291]:   File "/home/zentral/app/releases/2019.10.16-15.05.53-master-17e80f/zentral/utils/api_views.py", line 107, in dispatch
Mar 16 09:08:50 zentral-server.COMPANY.com gunicorn[1291]:     return super().dispatch(request, *args, **kwargs)
Mar 16 09:08:50 zentral-server.COMPANY.com gunicorn[1291]:   File "/home/zentral/app/venv/lib/python3.5/site-packages/django/views/generic/base.py", line 97, in dispatch
Mar 16 09:08:50 zentral-server.COMPANY.com gunicorn[1291]:     return handler(request, *args, **kwargs)
Mar 16 09:08:50 zentral-server.COMPANY.com gunicorn[1291]:   File "/home/zentral/app/releases/2019.10.16-15.05.53-master-17e80f/zentral/utils/api_views.py", line 147, in post
Mar 16 09:08:50 zentral-server.COMPANY.com gunicorn[1291]:     response_data = self.do_post(data)
Mar 16 09:08:50 zentral-server.COMPANY.com gunicorn[1291]:   File "/home/zentral/app/releases/2019.10.16-15.05.53-master-17e80f/zentral/contrib/jamf/views.py", line 119, in do_post
Mar 16 09:08:50 zentral-server.COMPANY.com gunicorn[1291]:     post_jamf_event(self.jamf_instance, self.user_agent, self.ip, data)
Mar 16 09:08:50 zentral-server.COMPANY.com gunicorn[1291]:   File "/home/zentral/app/releases/2019.10.16-15.05.53-master-17e80f/zentral/contrib/jamf/events/__init__.py", line 114, in post_jamf_event
Mar 16 09:08:50 zentral-server.COMPANY.com gunicorn[1291]:     "jamf_id": payload["jssID"],
Mar 16 09:08:50 zentral-server.COMPANY.com gunicorn[1291]: KeyError: 'jssID'`

**Comment by zacharysfisher** [comment]
I also see this error in JAMF Logs:

`2020-03-16 13:10:35,177 [ERROR] [neralPool-6] [WebhookProcessor         ] - Exception while trying to post event to https://zentral-server.COMPANY.com/jamf/post_event/r5G1KbsV1OIeAkJlNZO3OJQi6ZoK4dN0EwEUu7n0vaeg00nwxbMku1jpTBNBuXDveWe/ - 500 Internal Server Error`

**Comment by np5** [comment]
Sorry for the delay.

Looking at the gunicorn trace, It seems that you are running an old version of Zentral. We have changed the processing of the webhooks in this [commit](https://github.com/zentralopensource/zentral/commit/ea7cf76efad276532108b5023f6d650a2920a1d7#diff-061b56e2a91bf9289644ec2cb9e49153).

**Comment by zacharysfisher** [comment]
this has been solved.
