### ISSUE TITLE
backend not found

### ISSUE THREAD

**Issue by kmendell** [zentralopensource/zentral#998]
I have Zentral running and my device syncs to it, but when i try to connect/sync other devices (using santa) it just does not work

I see this error in the logs, im not sure what is causing this:

workers-1   | 2024-06-25 13:31:45,823 PID1 config DEBUG Get /apps/zentral.contrib.inventory/clients/0/backend config key
workers-1   | Traceback (most recent call last):
workers-1   |   File "/zentral/server/manage.py", line 10, in <module>
workers-1   |     execute_from_command_line(sys.argv)
workers-1   |   File "/opt/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
workers-1   |     utility.execute()
workers-1   |   File "/opt/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
workers-1   |     self.fetch_command(subcommand).run_from_argv(self.argv)
workers-1   |   File "/opt/venv/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
workers-1   |     self.execute(*args, **cmd_options)
workers-1   |   File "/opt/venv/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
workers-1   |     output = self.handle(*args, **options)
workers-1   |   File "/zentral/server/base/management/commands/runworkers.py", line 120, in handle
workers-1   |     for idx, worker in enumerate(sorted(get_workers(), key=lambda w: w.name)):
workers-1   |   File "/zentral/zentral/core/queues/workers.py", line 17, in get_workers
workers-1   |     workers_module = import_module("{}.workers".format(app))
workers-1   |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
workers-1   |     return _bootstrap._gcd_import(name[level:], package, level)
workers-1   |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
workers-1   |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
workers-1   |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
workers-1   |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
workers-1   |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
workers-1   |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
workers-1   |   File "/zentral/zentral/contrib/inventory/workers.py", line 3, in <module>
workers-1   |     from .clients import clients, InventoryError
workers-1   |   File "/zentral/zentral/contrib/inventory/clients/__init__.py", line 13, in <module>
workers-1   |     clients = list(get_clients(settings))
workers-1   |   File "/zentral/zentral/contrib/inventory/clients/__init__.py", line 9, in get_clients
workers-1   |     module = import_module(inv_cli_settings['backend'])
workers-1   |   File "/zentral/zentral/conf/config.py", line 272, in __getitem__
workers-1   |     value = self._collection[key]
workers-1   | KeyError: 'backend'

**Comment by np5** [comment]
It seems that you have an error in the configuration of your [inventory clients in `base.json`](https://github.com/zentralopensource/zentral/blob/c0366e820fe1eba768072c42b7983661eb2d2644/conf/start/zentral/base.json#L65-L71). Could you verify this ? Are you pulling inventory information from third party sources like another MDM ?

**Comment by kmendell** [comment]
it ended up being a "empty" backend source, i removed the dummy data source, but left the backend array there, so it was failing to find a source , removing that whole section seemed to fix it

**Comment by np5** [comment]
Thanks
